disable not working nexusIQ srv jenkins

diff --git a/src/build.jenkinsfile b/src/build.jenkinsfile
--- a/src/build.jenkinsfile
+++ b/src/build.jenkinsfile
@@ -183,33 +183,33 @@ pipeline {
                         zip zipFile: 'toolscoverage.zip', dir: 'toolscoverage', archive: true
                     }
                 }
-                stage ("Nexus IQ") {
-                    steps {
-                        echo "Starting NexusIQ scan for appId ${appId} against scan.zip"
-                        bat "powershell -Command \"& {Invoke-WebRequest -OutFile nexus-iq-cli.jar https://download.sonatype.com/clm/scanner/nexus-iq-cli-1.49.0-01.jar;}\""
-                        sh "mkdir scan"
-                        bat "cp -a src/tools/RAML.Tools/*.cs scan/"
-                        bat "cp -a src/tools/RAML.Tools/*.csproj scan/"
-                        bat "cp -a src/tools/RAML.Tools/*.config scan/"
-                        bat "cp -a *.nupkg scan/"
-                        zip zipFile: 'scan.zip', dir: 'scan', archive: true
-                        script {
-                            try {
-                                withCredentials([[$class: 'UsernamePasswordMultiBinding',
-                                    credentialsId: 'nexus-iq',
-                                    passwordVariable: 'IQ_PASSWORD',
-                                    usernameVariable: 'IQ_USERNAME']]) {
-                                        sh "${iqCmd} -a ${env.IQ_USERNAME}:${env.IQ_PASSWORD} scan.zip"
-                                }//withCredential 
-                            }//try
-                            catch(err) {
-                                        echo "Nexus IQ Scan Failed: ${err}"
-                                        if (ignoreErrors == false || failOnVulnerabilities == true)
-                                            throw err
-                            }//catch
-                        }//script
-                    }//steps
-                }
+                // stage ("Nexus IQ") {
+                //     steps {
+                //         echo "Starting NexusIQ scan for appId ${appId} against scan.zip"
+                //         bat "powershell -Command \"& {Invoke-WebRequest -OutFile nexus-iq-cli.jar https://download.sonatype.com/clm/scanner/nexus-iq-cli-1.49.0-01.jar;}\""
+                //         sh "mkdir scan"
+                //         bat "cp -a src/tools/RAML.Tools/*.cs scan/"
+                //         bat "cp -a src/tools/RAML.Tools/*.csproj scan/"
+                //         bat "cp -a src/tools/RAML.Tools/*.config scan/"
+                //         bat "cp -a *.nupkg scan/"
+                //         zip zipFile: 'scan.zip', dir: 'scan', archive: true
+                //         script {
+                //             try {
+                //                 withCredentials([[$class: 'UsernamePasswordMultiBinding',
+                //                     credentialsId: 'nexus-iq',
+                //                     passwordVariable: 'IQ_PASSWORD',
+                //                     usernameVariable: 'IQ_USERNAME']]) {
+                //                         sh "${iqCmd} -a ${env.IQ_USERNAME}:${env.IQ_PASSWORD} scan.zip"
+                //                 }//withCredential 
+                //             }//try
+                //             catch(err) {
+                //                         echo "Nexus IQ Scan Failed: ${err}"
+                //                         if (ignoreErrors == false || failOnVulnerabilities == true)
+                //                             throw err
+                //             }//catch
+                //         }//script
+                //     }//steps
+                // }
             }
         }
     }
